# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Desktop_Assistant_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jarvis(object):
    def setupUi(self, Jarvis):
        Jarvis.setObjectName("Jarvis")
        Jarvis.resize(376, 278)
        Jarvis.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(Jarvis)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1_gif = QtWidgets.QLabel(self.centralwidget)
        self.label_1_gif.setGeometry(QtCore.QRect(-10, -10, 391, 291))
        self.label_1_gif.setText("")
        self.label_1_gif.setPixmap(QtGui.QPixmap("C:\\Users\\alij7\\OneDrive\\Desktop\\Final_projec_desktop_assistant\database\\GUI material\\Personal Artificial Intelligence Assistant.gif"))
        self.label_1_gif.setScaledContents(True)
        self.label_1_gif.setObjectName("label_1_gif")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(240, 250, 56, 17))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(300, 250, 56, 17))
        self.pushButton_exit.setObjectName("pushButton_exit")
        Jarvis.setCentralWidget(self.centralwidget)

        self.retranslateUi(Jarvis)
        QtCore.QMetaObject.connectSlotsByName(Jarvis)

    def retranslateUi(self, Jarvis):
        _translate = QtCore.QCoreApplication.translate
        Jarvis.setWindowTitle(_translate("Jarvis", "Jarvis"))
        self.pushButton_start.setText(_translate("Jarvis", "Start"))
        self.pushButton_exit.setText(_translate("Jarvis", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jarvis = QtWidgets.QMainWindow()
    ui = Ui_Jarvis()
    ui.setupUi(Jarvis)
    Jarvis.show()
    sys.exit(app.exec_())
